---
# See: https://registry.hub.docker.com/_/swarm/

- name: retrieves and launches 'docker-swarm' image
  docker_container:
    image: '{{ docker_swarm_image }}'
    hostname: '{{ inventory_hostname }}'
    name: '{{ docker_swarm_container_name }}'
    env: '{{ docker_swarm_env }}'
    command:
      - 'join'
      - '--addr={{ docker_swarm_host_ip }}:2376'
      - '{{ docker_swarm_discovery }}'
    state: started
    # will be checked for a newer version of the image each time the task executes
    pull: yes
    # try to restart if the container exits
    restart_policy: always
    # it will try to restart 3 times before giving up
    restart_retries: 3
