---
# Common roles for all hosts

- name: 'updates apt cache & upgrades dist'
  apt:
    upgrade: 'yes'
    update_cache: 'yes'


- name: installs the necessary software
  apt:
    name: '{{ item }}'
    update_cache: 'yes'
    cache_valid_time: 3600
    state: 'latest'
  with_items:
    - '{{ common_packages }}'
