---

- include: tls.yml


- name: creates consul directories
  file:
    state: directory
    path: '{{ item }}'
  with_items:
    - '/etc/consul'


- name: uploads configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'config.json.j2', dest: '/etc/consul/config.json' }
  notify:
    # restart consul if configuration changes
    - 'restart consul'


# Fir for: One or more undefined variables: 'ansible_docker0' is undefined
- name: updates facts if docker0 is not defined
  action: setup
  when: ansible_docker0 is not defined


- include: run.yml
